reads: ".test/data/reads/" #Path to folder with reads
minReadsQual: 10
minReadsLength: 2000
threads_Flye: 20
### Number of threads to use for polishing (CPU for now, need to test GPU)
threads_Medaka : 4
### Number of batch to use in medaka (to lower if memory issue)
batch_Medaka : 100 
### MedakaModel (depend on Nanopore device and Guppy version)
medaka_model: "r1041_e82_400bps_sup_v4.2.0"

reference_genome: ".test/data/genomes/GCF_000008865.2_ASM886v2_genomic.fna"
metadata: ".test/data/metadata/metadata_test.csv"